---
title: "temporary Vernalization 04 file"
author: "XinYu Zhang"
date: "2023-11-08"
output: html_document
---



Exercise 1. Loading the dataset (raw_data)
```{r}
raw_data<-read.csv("C:/Users/XinYu Zhang/Downloads/raw_counts.csv")
```


Exercise 3.Fix the column names by removing "." because “.” is a wildcard character.
```{r}
library(stringr)
colnames(raw_data) <- str_remove(colnames(raw_data), fixed("."))
colnames(raw_data)
```


Exercise 4.Make a histogram of counts for each of the samples
Conclusion: the data is not normally distributed
```{r}
library(tidyr)
library(ggplot2)
library(dplyr)
#change data into long format
raw_data_long_format <- raw_data %>% 
  pivot_longer(c(-geneID), names_to="sample", values_to="count")

#Make a histogram
ggplot(raw_data_long_format, aes(x = count)) +
  geom_histogram(bins = 10, fill = "blue", color = "black") +
  xlim(c(0, 1000)) + 
  theme_minimal() +
  labs(title = "Histogram of Counts within Specified Range", x = "Count", y = "Frequency")
#Conclusion: Non-normal distribution

```

```{r}
raw_data <- raw_data[rowSums(raw_data[,-1] > 10) >= 3,]#For our subsequent analyses we want to reduce the data set to only those genes with some expression. In this case we will retain genes with > 10 reads in >= 3 samples
```

Exercise 5.check for correlation and visualize it
```{r}
library(tidyr)
library(dplyr)
library(gplots)
library(viridis)
library(stringr)

raw_data_limited <- raw_data[1:1000, -which(colnames(raw_data) == "geneID")]
# Adjust margins: c(bottom, left, top, right)
par(mar=c(4, 4, 2, 2))
#pairs(raw_data_limited) Large gra
raw_data_cor_table <- cor(raw_data_limited, use = "complete.obs")
print(raw_data_cor_table)#correlation table



raw_data_cor_table %>% gplots::heatmap.2(dendrogram="row", trace = "none", col=viridis::viridis(25, begin=.25), margins=c(7,8))
```


Exercise 6.Data Normalization
```{r}
sample.description_raw_data <-tibble(sample=colnames(raw_data)[-1])

data <- sample.description_raw_data%>% mutate(
    Pop = str_extract(sample,"bhr|ihl|kc|lv|sq|tm|wl|yo"), Vern = str_extract(sample, "v0|v1|v2|i0|i1|i2"),
    group = str_c(Vern, Pop, sep = "_"))
print(head(data))

#convert Elevation and Vernalization into factors for testing No vern,short vern, and long vern

sample.description_data <- data%>%
  mutate(Pop=factor(Pop), 
         Vern=factor(Vern,levels = c("v0","v1,v2"))) # setting the levels in this way makes "v0" the reference  

sample.description_data
```


Exercise 6. Normalization factor and plot
```{r}
#calculate the effective library size and normalization factors using the TMM method
library(edgeR)

counts.matrix_raw_data <- raw_data %>% select(-geneID) %>% as.matrix()
rownames(counts.matrix_raw_data) <- raw_data$geneID

dge.data_Normalization <- DGEList(counts=counts.matrix_raw_data, 
                    group=sample.description_raw_data$group)
dim(dge.data_Normalization) 
dge.data_Normalization <- calcNormFactors(dge.data_Normalization, method = "TMM")
dge.data_Normalization$sample # look at the normalization factors

plotMDS(dge.data_Normalization, method = "bcv") 
```

Exercise 8
```{r}
data_Normalization<-cpm(dge.data_Normalization)
data_Normalization_log <- log2(data_Normalization[,-1] + 1)

design <- model.matrix(~Pop+Vern,data = sample.description_data)
rownames(design) <- sample.description_data$samples
design


ncol(dge.data_Normalization)  # Number of samples in count data
nrow(design)  # Number of samples in design matrix


#Problem here
#dge.data_Normalization_dispersions <- estimateGLMCommonDisp(dge.data_Normalization,design,verbose = TRUE)

```

